# 🐍 Python 103 — Beginner Fundamentals
Welcome to Python 103! This guide will help you understand Python from the ground up. No prior programming experience required.

To ensure a deeper understanding and proper logic processing, please complete the 102 notebook (prerequisite) first.

# Pandas: Getting Started

*Pandas* - This is a Python library used for working with datasets.

- It does by helping us make sense of *DataFrames*

*DataFrames* - A form of two-dimensional structured data, like a table with columns and rows.

## Importing Data | CSV Files

*CSV* - Common Separated Values, and it's a file type that allows data to be saved in a table.

* Data presented in a tabular format is called *structured data*

In [ ]:
# Using Dictionaries to create a dataset of students and their grades

import pandas as pd

# Create a dictionary with student names as keys and their grades as values
student_grades = {
    "Alice": 85,
    "Bob": 92,
    "Charlie": 78,
    "David": 90,
    "Eve": 88
}   
# Convert the dictionary to a pandas DataFrame
pd.DataFrame.from_dict(student_grades, orient='index',columns=['Grade'])

# # Create a DataFrame from the dictionary
# df = pd.DataFrame(list(student_grades.items()), columns=['Student', 'Grade'])

# # Display the DataFrame
# print(df)

         Grade
Alice       85
Bob         92
Charlie     78
David       90
Eve         88

## Using JSON library

In [ ]:
# Using JSON library to parse a JSON string into a Python dictionary

import json

info = """ {
    "firstName": "Alice",
    "lastName": "Smith",
    "age": 30,
    "city": "Stockholm",
    "hobbies": ["reading", "traveling", "cooking"]
}"""

# Parse JSON string into Python dictionary
info_dict = json.loads(info)

info_dict

{'firstName': 'Alice',
 'lastName': 'Smith',
 'age': 30,
 'city': 'Stockholm',
 'hobbies': ['reading', 'traveling', 'cooking']}

In [10]:
info_dict["city"]

'Stockholm'

## Loading data from Compressed Files

In big data ere - it is likely to read data from compressed files.

One way to unzip the data is to use gzip.

In [11]:
import gzip 
import json

with gzip.open('data/poland-bankruptcy-data-2008.json.gz', 'rt') as f:
    poland_data = json.load(f)

In [17]:
# Check the type of poland_data
# type(poland_data)

# Check the keys in the poland_data dictionary
poland_data.keys()

dict_keys(['schema', 'data', 'metadata'])

In [ ]:
# Using the `from_dict`  Pandas function to read the data

# DataFrame()
df = pd.DataFrame.from_dict(poland_data['data'])

df.head()

,company_id,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9,...,feat_56,feat_57,feat_58,feat_59,feat_60,feat_61,feat_62,feat_63,feat_64,bankrupt
0,1,0.202350,0.46500,0.240380,1.5171,-14.547,0.510690,0.25366,0.91816,1.15190,...,0.13184,0.473950,0.86816,0.00024,8.5487,5.16550,107.740,3.38790,5.3440,False
1,2,0.030073,0.59563,0.186680,1.3382,-37.859,-0.000319,0.04167,0.67890,0.32356,...,0.12146,0.074369,0.87235,0.00000,1.5264,0.63305,622.660,0.58619,1.2381,False
2,3,0.257860,0.29949,0.665190,3.2211,71.799,0.000000,0.31877,2.33200,1.67620,...,0.16499,0.369210,0.81614,0.00000,4.3325,3.19850,65.215,5.59690,47.4660,False
3,4,0.227160,0.67850,0.042784,1.0828,-88.212,0.000000,0.28505,0.47384,1.32410,...,0.29358,0.706570,0.78617,0.48456,5.2309,5.06750,142.460,2.56210,3.0066,False
4,5,0.085443,0.38039,0.359230,1.9444,21.731,0.187900,0.10823,1.37140,1.11260,...,0.10124,0.163790,0.89876,0.00000,5.7035,4.00200,89.058,4.09840,5.9874,False

# Pickle File

Understand Pickling - Serialization and Deserializing.